name: pcic_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  dio: ^5.4.2+1
  path_provider: ^2.1.2
  provider: ^6.1.2
  url_strategy: ^0.2.0
  xml: ^6.5.0
  geolocator: ^11.0.0
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  latlong2: ^0.9.1
  location: ^6.0.1
  firebase_core: ^2.28.0
  intl: ^0.18.1
  firebase_auth: ^4.19.0
  screenshot: ^2.3.0
  gpx: ^2.2.2
  flutter_map_location_marker: ^8.0.8
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/pcic_logo.png"
  web:
    generate: true
    image_path: "assets/images/pcic_logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/pcic_logo.png
